# .github/workflows/build-main.yml
name: fractal main.c test on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-main:
    runs-on: ubuntu-latest  # 使用 Ubuntu (Linux)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up GCC
      run: |
        sudo apt-get update
        sudo apt-get install gcc

    - name: Compile main.c
      run: |
        gcc 03.A.Fractal/src/main.c 03.A.Fractal/src/image.c 03.A.Fractal/src/fractal.c -o main.exe

    - name: Verify main executable
      run: |
        if [ -f "./main.exe" ]; then
          echo "main.exe compilation successful."
        else
          echo "main.exe compilation failed."
          exit 1
        fi

    - name: Run main program (pass arguments)
      run: |
        ./main.exe sierpinski.pgm sierpinski 4
