# .github/workflows/build-test-main.yml
name: fractal test_main.c on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-main:
    runs-on: ubuntu-latest  # 使用 Ubuntu (Linux)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up GCC and Check library
      run: |
        sudo apt-get update
        sudo apt-get install gcc check

    - name: Compile test_main.c (Unit tests)
      run: |
        gcc 03.A.Fractal/src/test_main.c 03.A.Fractal/src/image.c 03.A.Fractal/src/fractal.c -o test_main.exe -lcheck

    - name: Verify test_main executable
      run: |
        if [ -f "./test_main.exe" ]; then
          echo "test_main.exe compilation successful."
        else
          echo "test_main.exe compilation failed."
          exit 1
        fi

    - name: Run Unit Tests
      run: |
        ./test_main.exe
