name: IO Flush Auto Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  setup_and_build:
    name: Set up and build program
    runs-on: ubuntu-latest

    steps:
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt install build-essential

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the program
        run: |
          cd 01.IO_flush/Code_auto
          gcc IO_Flush.c -o io_flush_auto

      - name: Upload build artifacts for testing
        uses: actions/upload-artifact@v4
        with:
          name: io_flush_auto
          path: ${{ github.workspace }}/01.IO_flush/Code_auto/io_flush_auto

  test:
    needs: setup_and_build
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: io_flush_auto
          path: Code_auto

      - name: Run tests without fflush()
        run: |
          cd Code_auto
          ./io_flush_auto -normal

      - name: Run tests with fflush()
        run: |
          cd Code_auto
          ./io_flush_auto -fflush

      - name: Run tests with '\n' output
        run: |
          cd Code_auto
          ./io_flush_auto -n

      - name: Run tests with redirected output (normal)
        run: |
          cd Code_auto
          ./io_flush_auto -redirect_normal

      - name: Run tests with redirected output (with fflush)
        run: |
          cd Code_auto
          ./io_flush_auto -redirect_fflush

      - name: Run tests with redirected output (with '\n')
        run: |
          cd Code_auto
          ./io_flush_auto -redirect_n

  save_results:
    needs: test
    name: Save results
    runs-on: ubuntu-latest
    steps:
      - name: Save test outputs to artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./output
