name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create output directory
      run: mkdir -p output

    - name: Compile and run program
      run: |
        cd 01.IO_flush/Code_test2  # 修改为实际的路径
        gcc test1.c -o test1_program
        chmod +x test1_program
        ./test1_program -normal  # 执行程序，生成输出文件

    - name: Run test program with different options
      run: |
        cd 01.IO_flush/Code_test2  # 修改为实际的路径
        chmod +x test1_program
        ./test1_program -normal
        ./test1_program -fflush
        ./test1_program -n
        ./test1_program -redirect_normal
        ./test1_program -redirect_fflush
        ./test1_program -redirect_n

    - name: List output directory contents
      run: |
        ls -R output/
        cat output/output_normal.txt  # 输出查看结果

    - name: Upload output files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output-files
        path: output/
