name: IO Flush Auto Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  setup_and_build:
    name: Настройка и запуск билда
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v4

      - name: Install gcc
        run: |
          sudo apt-get update
          sudo apt install build-essential

      - name: Build the test program
        run: |
          cd 01.IO_flush/Code_test2
          gcc test1.c -o test1_program

      - name: Upload build artifact for testing
        uses: actions/upload-artifact@v4
        with:
          name: test1_program
          path: ./01.IO_flush/Code_test2/test1_program

  test:
    needs: [setup_and_build]
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact for testing
        uses: actions/download-artifact@v4
        with:
          name: test1_program
          path: ./01.IO_flush/Code_test2

      - name: Run test program with different options
        run: |
          cd 01.IO_flush/Code_test2
          chmod +x test1_program
          ./test1_program -normal
          ./test1_program -fflush
          ./test1_program -n
          ./test1_program -redirect_normal
          ./test1_program -redirect_fflush
          ./test1_program -redirect_n

      - name: Check output files
        run: |
          ls output/
          cat output/output_normal.txt
          cat output/error_normal.txt
          cat output/output_fflush.txt
          cat output/error_fflush.txt
          cat output/output_with_n.txt
          cat output/error_with_n.txt
