name: IO Flush Auto Test

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    setup_and_build:
      name: Setup and Build
      runs-on: ubuntu-latest

      steps:
        - name: Install gcc
          run: |
            sudo apt-get update
            sudo apt install build-essential
            
        - name: Checkout source code
          uses: actions/checkout@v4
          
        - name: Compile the program
          run: |
            cd 01.IO_flush/Code_test2
            gcc test1.c -o io_flush_auto
            
        - name: Save build result for testing
          uses: actions/upload-artifact@v4
          with:
            name: io_flush_auto
            path: ${{ github.workspace }}/01.IO_flush/Code_test2/io_flush_auto
    
    test:
      needs:
        - setup_and_build
        
      name: Test
      runs-on: ubuntu-latest
      steps:
        - name: Download build result for testing
          uses: actions/download-artifact@v4
          with:
            name: io_flush_auto
            path: Code_test2
        
        - name: Create output directory
          run: |
            mkdir -p Code_test2/output  # 创建 output 目录

        - name: Run tests
          run: |
            cd Code_test2
            chmod 777 io_flush_auto
            ./io_flush_auto -normal
            ./io_flush_auto -fflush
            ./io_flush_auto -n
            ./io_flush_auto -redirect_normal
            ./io_flush_auto -redirect_fflush
            ./io_flush_auto -redirect_n
