name: IO Flush Auto Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  setup_and_build:
    name: Setup and Build Program
    runs-on: ubuntu-latest

    steps:
      - name: Install GCC
        run: |
          sudo apt-get update
          sudo apt install build-essential
          
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Build Program
        run: |
          cd 01.IO_flush/Code_test2
          gcc test1.c -o test1_program
          
      - name: Save Build Result for Testing
        uses: actions/upload-artifact@v4
        with:
          name: test1_program
          path: ${{ github.workspace }}/01.IO_flush/Code_test2/output

  test:
    needs:
      - setup_and_build

    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Result for Testing
        uses: actions/download-artifact@v4
        with:
          name: test1_program
          path: 01.IO_flush/Code_test2/output
        
      - name: Run Program
        run: |
          cd 01.IO_flush/Code_test2/output
          chmod 777 test1_program
          ./test1_program 1
          ./test1_program 2
          ./test1_program 3
          ./test1_program 4
