name: Memory Overcommit Windows Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSYS2 and Install MinGW
      run: |
        choco install msys2
        refreshenv
        pacman -Syu --noconfirm
        pacman -S mingw-w64-x86_64-gcc --noconfirm

    - name: Compile the C code
      run: |
        gcc 02.Memory_Overcommit/src/overcommit.c -o overcommit.exe

    - name: Run the compiled program
      run: |
        ./overcommit.exe
