name: Memory Overcommit Linux Test

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    setup_and_build:
      name: Setup and Build
      runs-on: ubuntu-latest

      steps:
        - name: Install GCC
          run: |
            sudo apt-get update
            sudo apt install build-essential
            
        - name: Checkout Source Code
          uses: actions/checkout@v4
            
        - name: Compile Program
          run: |
            cd 02.Memory_Overcommit/src
            gcc overcommit_linux.c -o overcommit_linux
            
        - name: Save Build Artifact
          uses: actions/upload-artifact@v4
          with:
            name: Linux_Codes
            path: ${{ github.workspace }}/02.Memory_Overcommit/src/overcommit_linux
