name: Build C Code on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MSYS2 and MinGW
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: |
          mingw-w64-x86_64-gcc


    - name: Compile C code
      shell: msys2 {0}
      run: |
        gcc 02.Memory_Overcommit/src/overcommit.c -o overcommit.exe


    - name: Verify Executable
      run: |
        if (Test-Path "./overcommit.exe") {
          Write-Output "Compilation successful. Executable created."
        } else {
          Write-Error "Compilation failed. Executable not found."
          exit 1
        }
