name: Memory Overcommit Windows Test

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    setup_and_build:
      name: Setup and Build on Windows
      runs-on: windows-latest

      steps:
        - name: Checkout Source Code
          uses: actions/checkout@v4
            
        - name: Install Visual Studio Build Tools
          run: |
            # Install Visual Studio Build Tools
            choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --quiet --norestart"
            # Install Python (if needed for your setup)
            choco install python --version 3.8
            
        - name: Set up MSVC environment
          run: |
            # Set up the Visual Studio command line environment for MSVC
            # This is needed for `cl` to work
            call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
            
        - name: Compile Program with MSVC
          run: |
            cd 02.Memory_Overcommit/src
            cl /EHsc overcommit.c /Fe:overcommit.exe

        - name: Save Build Artifact
          uses: actions/upload-artifact@v4
          with:
            name: Windows_Build_Codes
            path: ${{ github.workspace }}/02.Memory_Overcommit/src/overcommit.exe
