name: Build C Code on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Install MSYS2 and MinGW
      run: |
        # Install MSYS2 using Chocolatey
        choco install msys2 -y
        refreshenv

        # Update MSYS2 packages
        C:\tools\msys64\usr\bin\bash.exe -l -c "pacman -Syu --noconfirm"

        # Install MinGW GCC compiler
        C:\tools\msys64\usr\bin\bash.exe -l -c "pacman -S --needed --noconfirm mingw-w64-x86_64-gcc"

    - name: Compile the C code
      run: |
        # Add MinGW to PATH
        C:\tools\msys64\mingw64\bin\gcc.exe 02.Memory_Overcommit/src/overcommit.c -o overcommit.exe
